[project]
name = "guardian-pipeline"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { email = "marcaltmann@posteo.de" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
guardian-pipeline = "guardian_pipeline:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
